development:
  adapter: postgresql
  database: sample_app_dev
  username: mattghering
  password: seamus8242
  host: localhost
  encoding: UTF8

test:
  adapter: postgresql
  database: sample_app_test
  username: mattghering
  password: seamus8242
  host: localhost
  encoding: UTF8

production:
  adapter: postgresql
  database: sample_app_live
  username: mattghering
  password: seamus8242
  host: localhost
  encoding: UTF8
